# This is a basic workflow to help you get started with Actions

name: deploy to server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Setup SSH Private Key
        env:
          token_Private_Keys: ${{ secrets.TOKEN_PRIVATE_KEYS }}
        run: |
          mkdir -p ~/.ssh/
          echo "$token_Private_Keys" > ~/.ssh/id_rsa_github_token
          chmod 600 ~/.ssh/id_rsa_github_token
          ssh-keyscan 49.233.55.75 >> ~/.ssh/known_hosts

      # Runs a set of commands using the runners shell
      - name: Triger Update Script
        run: |
          ssh ubuntu@49.233.55.75 -i ~/.ssh/id_rsa_github_token "bash ~/CI/miniprogram-frontend.sh"
